[project]
name = "BlockJournProject"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.blockjournproject]
path = "contracts/blockjournproject.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }